
/*
 * Main.eq
 * Generated by Eqela Studio 2.0b7.4
 */
 class Main : LayerWidget{
    public void initialize() {
        base.initialize();
        set_size_request_override(px("60mm"), px("80mm"));
	add(CanvasWidget.for_colors(Color.instance("blue"),Color.instance("red")));
        
add(LabelWidget.for_string("UST")
		.set_font(Theme.font().modify("8mm bold color=white outline")));
		add(new TaskListWidget());
    }
}
